### ISSUE TITLE
Clarify endianness in the EEI design

### ISSUE THREAD

**Issue by lrettig** [ewasm/pm#11]

**Comment by axic** [comment]
I'm not sure what needs to be done here?

**Comment by lrettig** [comment]
I think I copied this over from another open task list somewhere. Is this decided once and for all? It is still frustrating to have to constantly swap endianness around when writing tests, example code, etc.

**Comment by axic** [comment]
I think it was, to what Hera is doing. Not sure where is the manual endianness swap happening?

**Comment by lrettig** [comment]
Well for instance `0xeD09375DC6B20050d242d1611af97eE4A6E93CAd` from  https://gist.github.com/axic/16158c5c88fbc7b1d09dfa8c658bc363 turns into this: https://github.com/lrettig/tests/blob/359a78b2008669039754cc9df94a06b994d066bd/src/GeneralStateTestsFiller/stEWASMTests/wrc20ChallengeFiller.yml#L40

I think I'm just complaining about the lack of human readability of little endian.

**Comment by axic** [comment]
Can you please migrate this question to the design repo?

**Comment by lrettig** [comment]
Like I said I copied this from a previous task list, it wasn't originally my task. I'll go ahead and close this unless anyone has objections -- I don't think we're seriously considering changing endianness now.
