### ISSUE TITLE
Add debugging via set_option to Hera

### ISSUE THREAD

**Issue by lrettig** [ewasm/pm#12]

**Comment by chfast** [comment]
Is this still relevant?

**Comment by lrettig** [comment]
Don't know, I think this came from a previous task list. Feel free to close if it's not relevant.

**Comment by chfast** [comment]
Please close it as I don't have rights to do it.

**Comment by jakelang** [comment]
Still candidate for inclusion in Hera, but not a priority

**Comment by axic** [comment]
It is tracked in https://github.com/ewasm/hera/issues/169
