### ISSUE TITLE
ewasm decision hangout #1

### ISSUE THREAD

**Issue by axic** [ewasm/pm#19]
View/recording link: http://youtu.be/BdRt7aHJBdI
Gitter channel: https://gitter.im/ewasm/Lobby

Date: July 5, 2018
Time: 4pm UTC (12am CST / 9am PST / 12pm EST / 6pm CEST)

It should last approx 30 - 60 minutes, depending on number of decisions to be made. It is a recurring meeting, every 2 weeks.

Agenda points must be added here before the meeting, otherwise they will not be discussed and the meeting may be cancelled if no agenda points are listed.

**Comment by axic** [comment]
I would like to propose the following issues to be discussed:
- https://github.com/ewasm/design/issues/103
- https://github.com/ewasm/design/issues/72
- https://github.com/ewasm/design/pull/39
- https://github.com/ewasm/design/issues/104

**Comment by chfast** [comment]
1. EEI redesign process.
2. Offload some design discussions to ethresear.ch, ewasm category.
3. Alternative gas counting implementation.

**Comment by axic** [comment]
Some outcomes from the call:
1. The "precompiles idea" is welcome and there were no voices against it. It needs a lot more research and discussion before it can be proposed to a wider audience (e.g. AllCoreDevs).
- some proposed precompile ideas should be implemented (with tests)
- metering options must be discussed / prototyped
- client wasm support must be reviewed
2. Issues should be created for the redesign process, gas counting and "use ethresearch for discussions"
3. Need to propose a decision process (ties into 2) and decide on the above design issues.
4. The next meeting should in depth discuss those already written proposals.

**Comment by chfast** [comment]
EEI redesign process: https://github.com/ewasm/design/issues/108

**Comment by axic** [comment]
Created follow up issue #20.
