### ISSUE TITLE
ewasm hangout #4

### ISSUE THREAD

**Issue by lrettig** [ewasm/pm#8]
View/recording link: https://www.youtube.com/watch?v=TNRSmybqeQc
Gitter channel: https://gitter.im/ewasm/Lobby

Date: June 21, 2018
Time: 5pm UTC (1am CST / 10am PST / 1pm EST / 7pm CEST)

It should last approx 30 - 60 minutes, depending on attendance. We plan to have it as recurring hangout, every 2-3 weeks.

Anyone is free (and encouraged) to attend. Feel free to propose agenda items and questions here.

**Comment by axic** [comment]
Next call is tracked in #18.
